openapi: 3.1.0
info:
  title: Federated API Discovery API
  version: '0.1.0'
  description: This produces metadata about APIs published by public sector organisations
    in the UK
paths:
  "/apis":
    get:
      description: Gets metadata about APIs published by public sector organisations
        in the UK
      operationId: retrieveAll
      responses:
        '200':
          description: A list of API metadata objects
          content:
            application/vnd.uk.gov.api.v1alpha+json:
              schema:
                $ref: './bulk-metadata-response.json'
      parameters:
        - name: correlation-id
          in: header
          description: A unique identifier to allow for correlating requests
          required: false
          schema:
            type: string
            format: uuid
