name: Build `examples/java` pushes

on:
  push:
    paths:
      - "examples/java/**"
      - ".github/workflows/examples-java-push.yml"
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: examples/java
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build
        run: ./gradlew clean build
      - name: Perform Static Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: examples-java-libs
          path: '**/build/libs/*'
          retention-days: 5
      - name: Upload Test reports
        uses: actions/upload-artifact@v2
        with:
          name: examples-java-reports
          path: '**/build/reports/*'
          retention-days: 5
      - name: Upload spring-boot manifest
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-manifest
          path: 'examples/java/spring-boot/manifest.yml'
          retention-days: 5
  deploy:
    environment: sandbox
    runs-on: ubuntu-18.04
    needs: test
#    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: examples-java-libs
      - uses: actions/download-artifact@v2
        with:
          name: spring-boot-manifest
      - name: Deploy to PaaS
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: cabinet-office-cddo-dsa-apis
          cf_space: sandbox
          command: push -f manifest.yml -p examples/java/spring-boot/build/libs/federated-api-model.jar
