name: Test OpenAPI doc is valid (Push)

on:
  push:
    paths:
      - '.github/workflows/openapi-docs-push.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"
      - "schemas/package.json"

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      - run: npm install
      - run: npm run lint:oas
