name: Test schemas are valid (Push)

on:
  push:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: 16
      - run: npm install
      - run: npm run test
