name: Test schemas are valid (Pull Request)

on:
  pull_request:
    paths:
      - "schemas/**"

permissions:
  contents: read
jobs:
  test:
    defaults:
      run:
        working-directory: schemas
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      - run: npm install
      - run: npm run test
